ProjectSoccer/Controllers/ClubsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjectSoccer.DataAccessLayer.Repositories;
using ProjectSoccer.Models;
using ProjectSoccer.Models.ViewModels;

namespace ProjectSoccer.Controllers
{
    public class ClubsController : Controller
    {
        private readonly ClubRepository _clubRepo;

        public ClubsController(ClubRepository clubRepo)
        {
            _clubRepo = clubRepo;
        }

        public async Task<IActionResult> Index()
        {
            var clubsList = await _clubRepo.GetAll();
            return View(clubsList);
        }
        public async Task<IActionResult> RefreshList()
        {
            var clubsListJson = JsonConvert.SerializeObject(await _clubRepo.GetAll());
            return Json(clubsListJson);
        }
        public async Task<IActionResult> Details(int id)
        {
            var club = await _clubRepo.GetById(id);
            if (club == null)
                return View("Error!");
            return View(club);
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _clubRepo.Delete(id);

            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] ClubViewModel clubvm)
        {
            var club = new Club { Name = clubvm.Name, ShortName = clubvm.ShortName, Logo = clubvm.Logo };
            await _clubRepo.Create(club);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var club = await _clubRepo.GetById(id);
            if (club == null)
                return View("Error!");
            return View(club);
        }
        [HttpPut]
        public async Task<IActionResult> Update(int id, [FromBody] Club club)
        {
            var existingClub = await _clubRepo.GetById(id);
            if (existingClub == null)
            {
                return NotFound();
            }
            if(club.Name is not "")
                existingClub.Name = club.Name;
            if (club.ShortName is not "")
                existingClub.ShortName = club.ShortName;
            if (club.Logo is not "")
                existingClub.Logo = club.Logo;

            await _clubRepo.Update(existingClub);
            return Ok();
        }

    }
}

ProjectSoccer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectSoccer.DataAccessLayer.Repositories;
using ProjectSoccer.Models;
using System.Diagnostics;

namespace ProjectSoccer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ClubRepository _clubRepository;
        private readonly PlayerRepository _playerRepository;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ClubRepository clubRepository, PlayerRepository playerRepository, ILogger<HomeController> logger)
        {
            _clubRepository = clubRepository;
            _playerRepository = playerRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult AboutMe()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectSoccer/Controllers/PlayersController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectSoccer.DataAccessLayer.Repositories;
using ProjectSoccer.Models;
using ProjectSoccer.Models.ViewModels;

namespace ProjectSoccer.Controllers
{
    public class PlayersController : Controller
    {
        private readonly PlayerRepository _playerRepo;
        private readonly ClubRepository _clubRepo;

        public PlayersController(PlayerRepository playerRepo, ClubRepository clubRepo)
        {
            _playerRepo = playerRepo;
            _clubRepo = clubRepo;
        }

        public async Task<IActionResult> Index()
        {
            var players = await _playerRepo.GetAll();
            return View(players);
        }
        public async Task<IActionResult> Details(int id)
        {
            var player = await _playerRepo.GetById(id);
            if (player == null) { return View("Error"); }
            return View(player);
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _playerRepo.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Create([FromBody] PlayerViewModel playervm)
        {
            var clubs = await _clubRepo.GetAll();
            var clubId = clubs.SingleOrDefault(x => x.ShortName == playervm.CurrentClub.ToUpper()).Id;
            if (clubId == null) { return View("Error"); }
            var player = new Player { FirstName = playervm.FirstName, LastName = playervm.LastName, DateOfBirth = DateTime.Now.AddYears(-playervm.Age), ClubId = clubId };
            await _playerRepo.Create(player);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var player = await _playerRepo.GetById(id);
            if (player == null)
                return View("Error!");
            return View(player);
        }
        [HttpPut]
        public async Task<IActionResult> Update(int id, [FromBody] Player player)
        {
            var existingPlayer = await _playerRepo.GetById(id);
            if(existingPlayer == null)
            { 
                return NotFound();
            }
            if (player.FirstName is not "")
                existingPlayer.FirstName = player.FirstName;
            if (player.LastName is not "")
                existingPlayer.LastName = player.LastName;
            if (player.ClubId is not 0)
                existingPlayer.ClubId = player.ClubId;
            if (player.DateOfBirth.Year is not 0)
                existingPlayer.DateOfBirth = player.DateOfBirth;

            await _playerRepo.Update(existingPlayer);
            return Ok();
        }
    }
}

ProjectSoccer/Views/Home/AboutMe.cshtml
@{
    ViewData["Title"] = "About Me";
}


<div class="text-center">
    <br />
    <h1 class="display-4">@ViewData["Title"]</h1>
    <br />
    <h3>
        Hey there! Welcome to my unique little corner of the web! 
    </h3>
    <h4>
        I'm a junior developer fueled by a burning desire to launch my career in a supportive work environment that embraces my growth. Armed with backend development skills and an insatiable curiosity for emerging technologies, I'm all about fresh ideas and out-of-the-box solutions.
        
        Sure, I may be a newbie, but don't underestimate my ability to soak up knowledge like a sponge. I've got a relentless work ethic and eagerness to learn from the seasoned pros around me. Together, we can take your organization to new heights.
        
        Beyond my coding prowess, I've got some hidden talents too. I used to groove as a Latin Dance Instructor and Board Member at the Marmara University Dance Society. Picture this: the first-ever mind-blowing salsa show, breaking records with pre-registrations, and packing the house with the most popular Latin classes ever seen!
        
        Oh, and let's not forget my gig as a fierce competitor and Assistant Instructor at the Aytunç Bentürk Dance Academy. I've got the moves and the drive to thrive in high-pressure dance contests.
        Now, imagine infusing that same passion, enthusiasm, and dedication into your organization. 
        <br />
        Yeah, I'm fired up! Thanks for considering my application. Let's chat soon and make some magic happen together!
    </h4>
    <br />
    <p style="animation:ease-in">Feel free to send a connection request on <a href="https://www.linkedin.com/in/emreaygener/">linkedin</a>.</p>
</div>

ProjectSoccer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center flex-row-reverse">
    <h1 class="display-4">Welcome</h1>
    <br />
    <h4>This is as Mvc Demo prepared for an interview.</h4>
    <br />
    <h5>The task was CRUD operations on <a asp-controller="Clubs" asp-action="Index">clubs</a> and <a asp-controller="Players" asp-action="Index">players</a>.</h5>
    <br />
    <h6>Hope you like what you see! :)</h6>
    <br />
    <p>To see other repos I have created <a href="https://github.com/emreaygener/">click here!</a></p>
    <br />
</div>